# Dockerfile

FROM selenium/hub:latest

MAINTAINER  Author Name <author@email.com>

RUN sudo apt-get -y update

RUN sudo apt-get install -y --no-install-recommends nginx curl && \
    sudo apt-get clean

# nginx

ADD docker/hub/wildcard_setitcredit_net.pem /etc/nginx/
ADD docker/hub/wildcard_setitcredit_net.cert.pem /etc/nginx/
ADD docker/hub/nginx-hub /etc/nginx/sites-available/

RUN sudo ln -s /etc/nginx/sites-available/nginx-hub /etc/nginx/sites-enabled/nginx-hub
RUN sudo openssl dhparam -out /etc/nginx/dhparams.pem 2048
RUN sudo sed -i '7i sudo service nginx start' /opt/bin/entry_point.sh

# filebeat

RUN sudo curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.5.0-amd64.deb
RUN sudo dpkg -i filebeat-5.5.0-amd64.deb
RUN sudo sed -i '8i sudo service filebeat start' /opt/bin/entry_point.sh

ADD docker/hub/filebeat.yml /etc/filebeat/

# datadog agent

RUN sudo apt-get update
RUN sudo apt-get install apt-transport-https

RUN sudo sh -c "echo 'deb https://apt.datadoghq.com/ stable main' > /etc/apt/sources.list.d/datadog.list"
RUN sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C7A7DA52

RUN sudo apt-get update
RUN sudo apt-get install datadog-agent

RUN sudo sh -c "sed 's/api_key:.*/api_key: 419e02815d44815d75e18edcab9d0833/' /etc/dd-agent/datadog.conf.example > /etc/dd-agent/datadog.conf"

RUN sudo sed -i '9i sudo service datadog-agent start' /opt/bin/entry_point.sh

# selenium

ADD build/dist/selenium-server-standalone-3.4.0.jar /opt/selenium/selenium-server-standalone.jar

RUN sudo sed -i '10i export SE_OPTS="-log /opt/selenium/hub.log"' /opt/bin/entry_point.sh

# done

RUN sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 4445

USER seluser

CMD ["/opt/bin/entry_point.sh"]
