# Dockerfile

FROM selenium/hub:latest

MAINTAINER  Author Name <author@email.com>

ADD build/dist/selenium-server-standalone-3.4.0.jar /opt/selenium/selenium-server-standalone.jar

RUN sudo apt-get -y update

RUN sudo apt-get install -y --no-install-recommends nginx && \
    sudo apt-get clean

RUN sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD docker/hub/wildcard_setitcredit_net.pem /etc/nginx/
ADD docker/hub/wildcard_setitcredit_net.cert.pem /etc/nginx/
ADD docker/hub/nginx-hub /etc/nginx/sites-available/

RUN sudo ln -s /etc/nginx/sites-available/nginx-hub /etc/nginx/sites-enabled/nginx-hub
RUN sudo openssl dhparam -out /etc/nginx/dhparams.pem 2048
RUN sudo sed -i '7i sudo service nginx start' /opt/bin/entry_point.sh

EXPOSE 4445

USER seluser

CMD ["/opt/bin/entry_point.sh"]
